# fly.toml app configuration file generated for pos-tracker-final on 2025-09-17T13:13:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pos-tracker-final'
primary_region = 'fra'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
